apiVersion: v1
kind: Secret
metadata:
  name: "{{.secretName}}"
  namespace: "{{.eksaSystemNamespace}}"
data:
  credentials: "{{.base64EncodedCredentials}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{.clusterName}}-nutanix-ccm-secret"
  namespace: "{{.eksaSystemNamespace}}"
stringData:
  nutanix-ccm-secret.yaml: "apiVersion: v1\nkind: Secret\nmetadata:\n  name: nutanix-creds\n
    \ namespace: kube-system\nstringData:\n  credentials: |\n    [\n      {\n        \"type\":
    \"basic_auth\", \n        \"data\": { \n          \"prismCentral\":{\n            \"username\":
    \"{{ .nutanixPCUsername }}\",\n            \"password\": \"{{ .nutanixPCPassword }}\"\n          },\n
    \         \"prismElements\": null\n        }\n      }\n    ]\n"
type: addons.cluster.x-k8s.io/resource-set
